class PreferenceHelper {
  static List<String>? countryPickerList = [];
  static final List<Map> countryList = [
    {"id": 1, "shortName": "AF", "name": "Afghanistan", "phoneCode": 93},
    {"id": 2, "shortName": "AL", "name": "Albania", "phoneCode": 355},
    {"id": 3, "shortName": "DZ", "name": "Algeria", "phoneCode": 213},
    {"id": 4, "shortName": "AS", "name": "American Samoa", "phoneCode": 1684},
    {"id": 5, "shortName": "AD", "name": "Andorra", "phoneCode": 376},
    {"id": 6, "shortName": "AO", "name": "Angola", "phoneCode": 244},
    {"id": 7, "shortName": "AI", "name": "Anguilla", "phoneCode": 1264},
    {"id": 8, "shortName": "AQ", "name": "Antarctica", "phoneCode": 0},
    {
      "id": 9,
      "shortName": "AG",
      "name": "Antigua And Barbuda",
      "phoneCode": 1268
    },
    {"id": 10, "shortName": "AR", "name": "Argentina", "phoneCode": 54},
    {"id": 11, "shortName": "AM", "name": "Armenia", "phoneCode": 374},
    {"id": 12, "shortName": "AW", "name": "Aruba", "phoneCode": 297},
    {"id": 13, "shortName": "AU", "name": "Australia", "phoneCode": 61},
    {"id": 14, "shortName": "AT", "name": "Austria", "phoneCode": 43},
    {"id": 15, "shortName": "AZ", "name": "Azerbaijan", "phoneCode": 994},
    {"id": 16, "shortName": "BS", "name": "Bahamas The", "phoneCode": 1242},
    {"id": 17, "shortName": "BH", "name": "Bahrain", "phoneCode": 973},
    {"id": 18, "shortName": "BD", "name": "Bangladesh", "phoneCode": 880},
    {"id": 19, "shortName": "BB", "name": "Barbados", "phoneCode": 1246},
    {"id": 20, "shortName": "BY", "name": "Belarus", "phoneCode": 375},
    {"id": 21, "shortName": "BE", "name": "Belgium", "phoneCode": 32},
    {"id": 22, "shortName": "BZ", "name": "Belize", "phoneCode": 501},
    {"id": 23, "shortName": "BJ", "name": "Benin", "phoneCode": 229},
    {"id": 24, "shortName": "BM", "name": "Bermuda", "phoneCode": 1441},
    {"id": 25, "shortName": "BT", "name": "Bhutan", "phoneCode": 975},
    {"id": 26, "shortName": "BO", "name": "Bolivia", "phoneCode": 591},
    {
      "id": 27,
      "shortName": "BA",
      "name": "Bosnia and Herzegovina",
      "phoneCode": 387
    },
    {"id": 28, "shortName": "BW", "name": "Botswana", "phoneCode": 267},
    {"id": 29, "shortName": "BV", "name": "Bouvet Island", "phoneCode": 0},
    {"id": 30, "shortName": "BR", "name": "Brazil", "phoneCode": 55},
    {
      "id": 31,
      "shortName": "IO",
      "name": "British Indian Ocean Territory",
      "phoneCode": 246
    },
    {"id": 32, "shortName": "BN", "name": "Brunei", "phoneCode": 673},
    {"id": 33, "shortName": "BG", "name": "Bulgaria", "phoneCode": 359},
    {"id": 34, "shortName": "BF", "name": "Burkina Faso", "phoneCode": 226},
    {"id": 35, "shortName": "BI", "name": "Burundi", "phoneCode": 257},
    {"id": 36, "shortName": "KH", "name": "Cambodia", "phoneCode": 855},
    {"id": 37, "shortName": "CM", "name": "Cameroon", "phoneCode": 237},
    {"id": 38, "shortName": "CA", "name": "Canada", "phoneCode": 1},
    {"id": 39, "shortName": "CV", "name": "Cape Verde", "phoneCode": 238},
    {"id": 40, "shortName": "KY", "name": "Cayman Islands", "phoneCode": 1345},
    {
      "id": 41,
      "shortName": "CF",
      "name": "Central African Republic",
      "phoneCode": 236
    },
    {"id": 42, "shortName": "TD", "name": "Chad", "phoneCode": 235},
    {"id": 43, "shortName": "CL", "name": "Chile", "phoneCode": 56},
    {"id": 44, "shortName": "CN", "name": "China", "phoneCode": 86},
    {"id": 45, "shortName": "CX", "name": "Christmas Island", "phoneCode": 61},
    {
      "id": 46,
      "shortName": "CC",
      "name": "Cocos (Keeling) Islands",
      "phoneCode": 672
    },
    {"id": 47, "shortName": "CO", "name": "Colombia", "phoneCode": 57},
    {"id": 48, "shortName": "KM", "name": "Comoros", "phoneCode": 269},
    {
      "id": 49,
      "shortName": "CG",
      "name": "Republic Of The Congo",
      "phoneCode": 242
    },
    {
      "id": 50,
      "shortName": "CD",
      "name": "Democratic Republic Of The Congo",
      "phoneCode": 242
    },
    {"id": 51, "shortName": "CK", "name": "Cook Islands", "phoneCode": 682},
    {"id": 52, "shortName": "CR", "name": "Costa Rica", "phoneCode": 506},
    {
      "id": 53,
      "shortName": "CI",
      "name": "Cote D'Ivoire (Ivory Coast)",
      "phoneCode": 225
    },
    {
      "id": 54,
      "shortName": "HR",
      "name": "Croatia (Hrvatska)",
      "phoneCode": 385
    },
    {"id": 55, "shortName": "CU", "name": "Cuba", "phoneCode": 53},
    {"id": 56, "shortName": "CY", "name": "Cyprus", "phoneCode": 357},
    {"id": 57, "shortName": "CZ", "name": "Czech Republic", "phoneCode": 420},
    {"id": 58, "shortName": "DK", "name": "Denmark", "phoneCode": 45},
    {"id": 59, "shortName": "DJ", "name": "Djibouti", "phoneCode": 253},
    {"id": 60, "shortName": "DM", "name": "Dominica", "phoneCode": 1767},
    {
      "id": 61,
      "shortName": "DO",
      "name": "Dominican Republic",
      "phoneCode": 1809
    },
    {"id": 62, "shortName": "TP", "name": "East Timor", "phoneCode": 670},
    {"id": 63, "shortName": "EC", "name": "Ecuador", "phoneCode": 593},
    {"id": 64, "shortName": "EG", "name": "Egypt", "phoneCode": 20},
    {"id": 65, "shortName": "SV", "name": "El Salvador", "phoneCode": 503},
    {
      "id": 66,
      "shortName": "GQ",
      "name": "Equatorial Guinea",
      "phoneCode": 240
    },
    {"id": 67, "shortName": "ER", "name": "Eritrea", "phoneCode": 291},
    {"id": 68, "shortName": "EE", "name": "Estonia", "phoneCode": 372},
    {"id": 69, "shortName": "ET", "name": "Ethiopia", "phoneCode": 251},
    {
      "id": 70,
      "shortName": "XA",
      "name": "External Territories of Australia",
      "phoneCode": 61
    },
    {"id": 71, "shortName": "FK", "name": "Falkland Islands", "phoneCode": 500},
    {"id": 72, "shortName": "FO", "name": "Faroe Islands", "phoneCode": 298},
    {"id": 73, "shortName": "FJ", "name": "Fiji Islands", "phoneCode": 679},
    {"id": 74, "shortName": "FI", "name": "Finland", "phoneCode": 358},
    {"id": 75, "shortName": "FR", "name": "France", "phoneCode": 33},
    {"id": 76, "shortName": "GF", "name": "French Guiana", "phoneCode": 594},
    {"id": 77, "shortName": "PF", "name": "French Polynesia", "phoneCode": 689},
    {
      "id": 78,
      "shortName": "TF",
      "name": "French Southern Territories",
      "phoneCode": 0
    },
    {"id": 79, "shortName": "GA", "name": "Gabon", "phoneCode": 241},
    {"id": 80, "shortName": "GM", "name": "Gambia The", "phoneCode": 220},
    {"id": 81, "shortName": "GE", "name": "Georgia", "phoneCode": 995},
    {"id": 82, "shortName": "DE", "name": "Germany", "phoneCode": 49},
    {"id": 83, "shortName": "GH", "name": "Ghana", "phoneCode": 233},
    {"id": 84, "shortName": "GI", "name": "Gibraltar", "phoneCode": 350},
    {"id": 85, "shortName": "GR", "name": "Greece", "phoneCode": 30},
    {"id": 86, "shortName": "GL", "name": "Greenland", "phoneCode": 299},
    {"id": 87, "shortName": "GD", "name": "Grenada", "phoneCode": 1473},
    {"id": 88, "shortName": "GP", "name": "Guadeloupe", "phoneCode": 590},
    {"id": 89, "shortName": "GU", "name": "Guam", "phoneCode": 1671},
    {"id": 90, "shortName": "GT", "name": "Guatemala", "phoneCode": 502},
    {
      "id": 91,
      "shortName": "XU",
      "name": "Guernsey and Alderney",
      "phoneCode": 44
    },
    {"id": 92, "shortName": "GN", "name": "Guinea", "phoneCode": 224},
    {"id": 93, "shortName": "GW", "name": "Guinea-Bissau", "phoneCode": 245},
    {"id": 94, "shortName": "GY", "name": "Guyana", "phoneCode": 592},
    {"id": 95, "shortName": "HT", "name": "Haiti", "phoneCode": 509},
    {
      "id": 96,
      "shortName": "HM",
      "name": "Heard and McDonald Islands",
      "phoneCode": 0
    },
    {"id": 97, "shortName": "HN", "name": "Honduras", "phoneCode": 504},
    {"id": 98, "shortName": "HK", "name": "Hong Kong S.A.R.", "phoneCode": 852},
    {"id": 99, "shortName": "HU", "name": "Hungary", "phoneCode": 36},
    {"id": 100, "shortName": "IS", "name": "Iceland", "phoneCode": 354},
    {"id": 101, "shortName": "IN", "name": "India", "phoneCode": 91},
    {"id": 102, "shortName": "ID", "name": "Indonesia", "phoneCode": 62},
    {"id": 103, "shortName": "IR", "name": "Iran", "phoneCode": 98},
    {"id": 104, "shortName": "IQ", "name": "Iraq", "phoneCode": 964},
    {"id": 105, "shortName": "IE", "name": "Ireland", "phoneCode": 353},
    {"id": 106, "shortName": "IL", "name": "Israel", "phoneCode": 972},
    {"id": 107, "shortName": "IT", "name": "Italy", "phoneCode": 39},
    {"id": 108, "shortName": "JM", "name": "Jamaica", "phoneCode": 1876},
    {"id": 109, "shortName": "JP", "name": "Japan", "phoneCode": 81},
    {"id": 110, "shortName": "XJ", "name": "Jersey", "phoneCode": 44},
    {"id": 111, "shortName": "JO", "name": "Jordan", "phoneCode": 962},
    {"id": 112, "shortName": "KZ", "name": "Kazakhstan", "phoneCode": 7},
    {"id": 113, "shortName": "KE", "name": "Kenya", "phoneCode": 254},
    {"id": 114, "shortName": "KI", "name": "Kiribati", "phoneCode": 686},
    {"id": 115, "shortName": "KP", "name": "Korea North", "phoneCode": 850},
    {"id": 116, "shortName": "KR", "name": "Korea South", "phoneCode": 82},
    {"id": 117, "shortName": "KW", "name": "Kuwait", "phoneCode": 965},
    {"id": 118, "shortName": "KG", "name": "Kyrgyzstan", "phoneCode": 996},
    {"id": 119, "shortName": "LA", "name": "Laos", "phoneCode": 856},
    {"id": 120, "shortName": "LV", "name": "Latvia", "phoneCode": 371},
    {"id": 121, "shortName": "LB", "name": "Lebanon", "phoneCode": 961},
    {"id": 122, "shortName": "LS", "name": "Lesotho", "phoneCode": 266},
    {"id": 123, "shortName": "LR", "name": "Liberia", "phoneCode": 231},
    {"id": 124, "shortName": "LY", "name": "Libya", "phoneCode": 218},
    {"id": 125, "shortName": "LI", "name": "Liechtenstein", "phoneCode": 423},
    {"id": 126, "shortName": "LT", "name": "Lithuania", "phoneCode": 370},
    {"id": 127, "shortName": "LU", "name": "Luxembourg", "phoneCode": 352},
    {"id": 128, "shortName": "MO", "name": "Macau S.A.R.", "phoneCode": 853},
    {"id": 129, "shortName": "MK", "name": "Macedonia", "phoneCode": 389},
    {"id": 130, "shortName": "MG", "name": "Madagascar", "phoneCode": 261},
    {"id": 131, "shortName": "MW", "name": "Malawi", "phoneCode": 265},
    {"id": 132, "shortName": "MY", "name": "Malaysia", "phoneCode": 60},
    {"id": 133, "shortName": "MV", "name": "Maldives", "phoneCode": 960},
    {"id": 134, "shortName": "ML", "name": "Mali", "phoneCode": 223},
    {"id": 135, "shortName": "MT", "name": "Malta", "phoneCode": 356},
    {"id": 136, "shortName": "XM", "name": "Man (Isle of)", "phoneCode": 44},
    {
      "id": 137,
      "shortName": "MH",
      "name": "Marshall Islands",
      "phoneCode": 692
    },
    {"id": 138, "shortName": "MQ", "name": "Martinique", "phoneCode": 596},
    {"id": 139, "shortName": "MR", "name": "Mauritania", "phoneCode": 222},
    {"id": 140, "shortName": "MU", "name": "Mauritius", "phoneCode": 230},
    {"id": 141, "shortName": "YT", "name": "Mayotte", "phoneCode": 269},
    {"id": 142, "shortName": "MX", "name": "Mexico", "phoneCode": 52},
    {"id": 143, "shortName": "FM", "name": "Micronesia", "phoneCode": 691},
    {"id": 144, "shortName": "MD", "name": "Moldova", "phoneCode": 373},
    {"id": 145, "shortName": "MC", "name": "Monaco", "phoneCode": 377},
    {"id": 146, "shortName": "MN", "name": "Mongolia", "phoneCode": 976},
    {"id": 147, "shortName": "MS", "name": "Montserrat", "phoneCode": 1664},
    {"id": 148, "shortName": "MA", "name": "Morocco", "phoneCode": 212},
    {"id": 149, "shortName": "MZ", "name": "Mozambique", "phoneCode": 258},
    {"id": 150, "shortName": "MM", "name": "Myanmar", "phoneCode": 95},
    {"id": 151, "shortName": "NA", "name": "Namibia", "phoneCode": 264},
    {"id": 152, "shortName": "NR", "name": "Nauru", "phoneCode": 674},
    {"id": 153, "shortName": "NP", "name": "Nepal", "phoneCode": 977},
    {
      "id": 154,
      "shortName": "AN",
      "name": "Netherlands Antilles",
      "phoneCode": 599
    },
    {"id": 155, "shortName": "NL", "name": "Netherlands The", "phoneCode": 31},
    {"id": 156, "shortName": "NC", "name": "New Caledonia", "phoneCode": 687},
    {"id": 157, "shortName": "NZ", "name": "New Zealand", "phoneCode": 64},
    {"id": 158, "shortName": "NI", "name": "Nicaragua", "phoneCode": 505},
    {"id": 159, "shortName": "NE", "name": "Niger", "phoneCode": 227},
    {"id": 160, "shortName": "NG", "name": "Nigeria", "phoneCode": 234},
    {"id": 161, "shortName": "NU", "name": "Niue", "phoneCode": 683},
    {"id": 162, "shortName": "NF", "name": "Norfolk Island", "phoneCode": 672},
    {
      "id": 163,
      "shortName": "MP",
      "name": "Northern Mariana Islands",
      "phoneCode": 1670
    },
    {"id": 164, "shortName": "NO", "name": "Norway", "phoneCode": 47},
    {"id": 165, "shortName": "OM", "name": "Oman", "phoneCode": 968},
    {"id": 166, "shortName": "PK", "name": "Pakistan", "phoneCode": 92},
    {"id": 167, "shortName": "PW", "name": "Palau", "phoneCode": 680},
    {
      "id": 168,
      "shortName": "PS",
      "name": "Palestinian Territory Occupied",
      "phoneCode": 970
    },
    {"id": 169, "shortName": "PA", "name": "Panama", "phoneCode": 507},
    {
      "id": 170,
      "shortName": "PG",
      "name": "Papua new Guinea",
      "phoneCode": 675
    },
    {"id": 171, "shortName": "PY", "name": "Paraguay", "phoneCode": 595},
    {"id": 172, "shortName": "PE", "name": "Peru", "phoneCode": 51},
    {"id": 173, "shortName": "PH", "name": "Philippines", "phoneCode": 63},
    {"id": 174, "shortName": "PN", "name": "Pitcairn Island", "phoneCode": 0},
    {"id": 175, "shortName": "PL", "name": "Poland", "phoneCode": 48},
    {"id": 176, "shortName": "PT", "name": "Portugal", "phoneCode": 351},
    {"id": 177, "shortName": "PR", "name": "Puerto Rico", "phoneCode": 1787},
    {"id": 178, "shortName": "QA", "name": "Qatar", "phoneCode": 974},
    {"id": 179, "shortName": "RE", "name": "Reunion", "phoneCode": 262},
    {"id": 180, "shortName": "RO", "name": "Romania", "phoneCode": 40},
    {"id": 181, "shortName": "RU", "name": "Russia", "phoneCode": 70},
    {"id": 182, "shortName": "RW", "name": "Rwanda", "phoneCode": 250},
    {"id": 183, "shortName": "SH", "name": "Saint Helena", "phoneCode": 290},
    {
      "id": 184,
      "shortName": "KN",
      "name": "Saint Kitts And Nevis",
      "phoneCode": 1869
    },
    {"id": 185, "shortName": "LC", "name": "Saint Lucia", "phoneCode": 1758},
    {
      "id": 186,
      "shortName": "PM",
      "name": "Saint Pierre and Miquelon",
      "phoneCode": 508
    },
    {
      "id": 187,
      "shortName": "VC",
      "name": "Saint Vincent And The Grenadines",
      "phoneCode": 1784
    },
    {"id": 188, "shortName": "WS", "name": "Samoa", "phoneCode": 684},
    {"id": 189, "shortName": "SM", "name": "San Marino", "phoneCode": 378},
    {
      "id": 190,
      "shortName": "ST",
      "name": "Sao Tome and Principe",
      "phoneCode": 239
    },
    {"id": 191, "shortName": "SA", "name": "Saudi Arabia", "phoneCode": 966},
    {"id": 192, "shortName": "SN", "name": "Senegal", "phoneCode": 221},
    {"id": 193, "shortName": "RS", "name": "Serbia", "phoneCode": 381},
    {"id": 194, "shortName": "SC", "name": "Seychelles", "phoneCode": 248},
    {"id": 195, "shortName": "SL", "name": "Sierra Leone", "phoneCode": 232},
    {"id": 196, "shortName": "SG", "name": "Singapore", "phoneCode": 65},
    {"id": 197, "shortName": "SK", "name": "Slovakia", "phoneCode": 421},
    {"id": 198, "shortName": "SI", "name": "Slovenia", "phoneCode": 386},
    {
      "id": 199,
      "shortName": "XG",
      "name": "Smaller Territories of the UK",
      "phoneCode": 44
    },
    {"id": 200, "shortName": "SB", "name": "Solomon Islands", "phoneCode": 677},
    {"id": 201, "shortName": "SO", "name": "Somalia", "phoneCode": 252},
    {"id": 202, "shortName": "ZA", "name": "South Africa", "phoneCode": 27},
    {"id": 203, "shortName": "GS", "name": "South Georgia", "phoneCode": 0},
    {"id": 204, "shortName": "SS", "name": "South Sudan", "phoneCode": 211},
    {"id": 205, "shortName": "ES", "name": "Spain", "phoneCode": 34},
    {"id": 206, "shortName": "LK", "name": "Sri Lanka", "phoneCode": 94},
    {"id": 207, "shortName": "SD", "name": "Sudan", "phoneCode": 249},
    {"id": 208, "shortName": "SR", "name": "Suriname", "phoneCode": 597},
    {
      "id": 209,
      "shortName": "SJ",
      "name": "Svalbard And Jan Mayen Islands",
      "phoneCode": 47
    },
    {"id": 210, "shortName": "SZ", "name": "Swaziland", "phoneCode": 268},
    {"id": 211, "shortName": "SE", "name": "Sweden", "phoneCode": 46},
    {"id": 212, "shortName": "CH", "name": "Switzerland", "phoneCode": 41},
    {"id": 213, "shortName": "SY", "name": "Syria", "phoneCode": 963},
    {"id": 214, "shortName": "TW", "name": "Taiwan", "phoneCode": 886},
    {"id": 215, "shortName": "TJ", "name": "Tajikistan", "phoneCode": 992},
    {"id": 216, "shortName": "TZ", "name": "Tanzania", "phoneCode": 255},
    {"id": 217, "shortName": "TH", "name": "Thailand", "phoneCode": 66},
    {"id": 218, "shortName": "TG", "name": "Togo", "phoneCode": 228},
    {"id": 219, "shortName": "TK", "name": "Tokelau", "phoneCode": 690},
    {"id": 220, "shortName": "TO", "name": "Tonga", "phoneCode": 676},
    {
      "id": 221,
      "shortName": "TT",
      "name": "Trinidad And Tobago",
      "phoneCode": 1868
    },
    {"id": 222, "shortName": "TN", "name": "Tunisia", "phoneCode": 216},
    {"id": 223, "shortName": "TR", "name": "Turkey", "phoneCode": 90},
    {"id": 224, "shortName": "TM", "name": "Turkmenistan", "phoneCode": 7370},
    {
      "id": 225,
      "shortName": "TC",
      "name": "Turks And Caicos Islands",
      "phoneCode": 1649
    },
    {"id": 226, "shortName": "TV", "name": "Tuvalu", "phoneCode": 688},
    {"id": 227, "shortName": "UG", "name": "Uganda", "phoneCode": 256},
    {"id": 228, "shortName": "UA", "name": "Ukraine", "phoneCode": 380},
    {
      "id": 229,
      "shortName": "AE",
      "name": "United Arab Emirates",
      "phoneCode": 971
    },
    {"id": 230, "shortName": "GB", "name": "United Kingdom", "phoneCode": 44},
    {"id": 231, "shortName": "US", "name": "United States", "phoneCode": 1},
    {
      "id": 232,
      "shortName": "UM",
      "name": "United States Minor Outlying Islands",
      "phoneCode": 1
    },
    {"id": 233, "shortName": "UY", "name": "Uruguay", "phoneCode": 598},
    {"id": 234, "shortName": "UZ", "name": "Uzbekistan", "phoneCode": 998},
    {"id": 235, "shortName": "VU", "name": "Vanuatu", "phoneCode": 678},
    {
      "id": 236,
      "shortName": "VA",
      "name": "Vatican City State (Holy See)",
      "phoneCode": 39
    },
    {"id": 237, "shortName": "VE", "name": "Venezuela", "phoneCode": 58},
    {"id": 238, "shortName": "VN", "name": "Vietnam", "phoneCode": 84},
    {
      "id": 239,
      "shortName": "VG",
      "name": "Virgin Islands (British)",
      "phoneCode": 1284
    },
    {
      "id": 240,
      "shortName": "VI",
      "name": "Virgin Islands (US)",
      "phoneCode": 1340
    },
    {
      "id": 241,
      "shortName": "WF",
      "name": "Wallis And Futuna Islands",
      "phoneCode": 681
    },
    {"id": 242, "shortName": "EH", "name": "Western Sahara", "phoneCode": 212},
    {"id": 243, "shortName": "YE", "name": "Yemen", "phoneCode": 967},
    {"id": 244, "shortName": "YU", "name": "Yugoslavia", "phoneCode": 38},
    {"id": 245, "shortName": "ZM", "name": "Zambia", "phoneCode": 260},
    {"id": 246, "shortName": "ZW", "name": "Zimbabwe", "phoneCode": 263}
  ];
}
